version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    # Only allow updates to the lockfile for pip and
    # ignore any version updates that affect the manifest
    #versioning-strategy: lockfile-only
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
