name: "Hello World"
description: "Greet someone and record the time"
inputs:
  message: # id of input
    description: "Who to greet"
    required: true
    default: "World"
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "comment-index.js"
