name: dummy-check

on:
  label:
    types: [created, deleted]

jobs:
  build_deploy:
    name: Dummy check
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm check-complete
      - run: |
          echo "Hello ${{ github.event }}!"
          echo "- in ${{ github.eventlabel }}!"
